enum AppConstants {
    static let subscriptionsTitle = "Subscriptions"
    static let setupIncomplete = "Setup Incomplete"
    static let subscriptionsGroupDescription = "Connect your card or account to start tracking your subscriptions."
    static let completeSetupButton = "Complete Setup"
    static let createSubscriptionTitle = "Create Subscription"
    static let saveButton = "Save"
    static let chooseService = "Choose a service"
    static let nameField = "Name"
    static let amountField = "Amount"
    static let categoryField = "Category"
    static let startDateField = "Start Date"
    static let frequencyField = "Frequency"
    static let activeField = "Active"
    static let servicePickerTitle = "Services"
    static let categoryPickerTitle = "Category"
    static let datePickerTitle = "Start Date"
    static let frequencyPickerTitle = "Frequency"
    static let doneButton = "Done"
    static let searchPlaceholder = "Search"
    static let emptyString = ""
    static let defaultAmount = "$0"
    static let successAlertTitle = "You're all set!"
    static let backToHomeButton = "Back to Home"
}
